name: spotify-forecast
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - statsmodels
  - streamlit
  - gradio
  - jupyter
  - tqdm
  - pip:
      - prophet  # Installing via pip is faster and more reliable
